# Generated by Django 4.2.8 on 2024-01-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firsname', models.CharField(max_length=50, verbose_name='Adı')),
                ('lastname', models.CharField(max_length=50, verbose_name='Soyadı')),
                ('companyname', models.CharField(max_length=150, verbose_name='Şirket Adı')),
                ('adres', models.CharField(max_length=150, verbose_name='Adresi')),
                ('title', models.CharField(max_length=150, verbose_name='Konu')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail Adresi')),
                ('phonenumber', models.CharField(max_length=50, verbose_name='Telefon Numarası')),
                ('text', models.TextField(verbose_name='İletişim Mesajı')),
            ],
        ),
    ]
