# Generated by Django 4.2.8 on 2024-01-18 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='firsname',
            new_name='firstname',
        ),
    ]
